version: "3.3"
services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD?REQUIRED}' ]
      interval: 1m
      timeout: 10s
      retries: 5
    networks:
      - ${PROJECT_NAME}
  wordpress:
    depends_on:
      - db
    image: wordpress:${WORDPRESS_VERSION:-latest}
    container_name: ${PROJECT_NAME:-wordpress}
    restart: unless-stopped
    env_file: .env
    volumes:
       - ${WORDPRESS_DATA_DIR}:/var/www/html
    networks:
      - ${PROJECT_NAME}
  nginx:
    depends_on:
      - wordpress
    image: nginx:${NGINX_VERSION:-latest}
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ${WORDPRESS_DATA_DIR}:/var/www/html
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ${PROJECT_NAME}

volumes:
  dbdata:

networks:
  wordpress:
    driver: bridge